services:
  api:
    build: .
    container_name: waste-api
    command: python api.py
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    restart: always

  streamlit:
    build: .
    container_name: waste-app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
    restart: always